"""Training, generation, and evaluation hyperparameters."""

MAX_LEN = 512
MAX_NEW_TOKENS = 128
MAX_JUDGE_NEW_TOKENS = 200

GENERATION_BATCH_SIZE = 8
DO_SAMPLE = False
REPETITION_PENALTY = 1.1

TRAIN_TEST_SPLIT = 0.2
RANDOM_STATE = 42

NUM_EPOCHS = 7
LEARNING_RATE = 1e-5
BATCH_SIZE = 6
GRAD_CLIP_NORM = 1.0
